# Common Training Configuration
paths:
  data_dir: "../../data/processed/split_features"
  model_dir: "../../models"
  report_dir: "../../reports/logs"
  fig_dir: "../../reports/figs"

features:
  categorical: ["line_name", "season"]
  target: "y"
  outlier_cap_z: 3.0
  normalize_by_line: false
  needs_denormalization: false

train:
  early_stopping_rounds: 100
  eval_freq: 50
  seed: 42
  num_threads: 8
